name: game_template
description: A mobile game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.17.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^2.0.0
  cupertino_icons: ^1.0.2
  go_router: ^6.0.1
  logging: ^1.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  function_tree: ^0.8.13
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.1.1+1
  scaffold_gradient_background: ^1.0.3+1
  lottie: ^2.3.2
  font_awesome_flutter: ^10.4.0
  material_dialogs: ^1.1.4
  uuid: ^3.0.7
  introduction_screen: ^3.1.8

  # If you don't need one of the following dependencies,
  # delete the relevant line below, and get rid of any Dart code
  # that references the dependency.
  firebase_core: ^2.13.0 # Needed for Crashlytics below
  firebase_crashlytics: ^3.0.3 # Error reporting
  games_services: ^3.0.0 # Achievements and leaderboards
  google_mobile_ads: ^2.0.1 # Ads
  in_app_purchase: ^3.0.1 # In-app purchases
  firebase_database: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/animations/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: Saira
      fonts:
        - asset: assets/fonts/Saira/Saira-Regular.ttf
        - asset: assets/fonts/Saira/Saira-Medium.ttf
        - asset: assets/fonts/Saira/Saira-Bold.ttf
        - asset: assets/fonts/Saira/Saira-Light.ttf
    - family: Darumadrop
      fonts:
        - asset: assets/fonts/Darumadrop/DarumadropOne-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/icon-adaptive-foreground.png'
